/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// AddClientToClientSetRequest
    /// </summary>
    [DataContract(Name = "AddClientToClientSet_request")]
    public partial class AddClientToClientSetRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddClientToClientSetRequest" /> class.
        /// </summary>
        /// <param name="clientID">The ID of the @see(ALClient) that is being moved. Method will fail if the client cannot be found.</param>
        /// <param name="clientSetID">The ID of the @see(ALClientSet) that this @see(ALClient) is going to be moved to. Method will fail if the clientset cannot be found..</param>
        public AddClientToClientSetRequest(int clientID = default(int), int clientSetID = default(int))
        {
            this.ClientID = clientID;
            this.ClientSetID = clientSetID;
        }

        /// <summary>
        /// The ID of the @see(ALClient) that is being moved. Method will fail if the client cannot be found
        /// </summary>
        /// <value>The ID of the @see(ALClient) that is being moved. Method will fail if the client cannot be found</value>
        [DataMember(Name = "ClientID", EmitDefaultValue = false)]
        public int ClientID { get; set; }

        /// <summary>
        /// The ID of the @see(ALClientSet) that this @see(ALClient) is going to be moved to. Method will fail if the clientset cannot be found.
        /// </summary>
        /// <value>The ID of the @see(ALClientSet) that this @see(ALClient) is going to be moved to. Method will fail if the clientset cannot be found.</value>
        [DataMember(Name = "ClientSetID", EmitDefaultValue = false)]
        public int ClientSetID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddClientToClientSetRequest {\n");
            sb.Append("  ClientID: ").Append(ClientID).Append("\n");
            sb.Append("  ClientSetID: ").Append(ClientSetID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
