/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// AUTHGetClientLoginsRequest
    /// </summary>
    [DataContract(Name = "AUTH_GetClientLogins_request")]
    public partial class AUTHGetClientLoginsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AUTHGetClientLoginsRequest" /> class.
        /// </summary>
        /// <param name="includeDisabled">True if you want disabled logins included in your result, false if you want just enabled logins.</param>
        /// <param name="siteId">Id of the CM Site (typically 1).</param>
        public AUTHGetClientLoginsRequest(bool includeDisabled = default(bool), int siteId = default(int))
        {
            this.IncludeDisabled = includeDisabled;
            this.SiteId = siteId;
        }

        /// <summary>
        /// True if you want disabled logins included in your result, false if you want just enabled logins
        /// </summary>
        /// <value>True if you want disabled logins included in your result, false if you want just enabled logins</value>
        [DataMember(Name = "IncludeDisabled", EmitDefaultValue = true)]
        public bool IncludeDisabled { get; set; }

        /// <summary>
        /// Id of the CM Site (typically 1)
        /// </summary>
        /// <value>Id of the CM Site (typically 1)</value>
        [DataMember(Name = "SiteId", EmitDefaultValue = false)]
        public int SiteId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AUTHGetClientLoginsRequest {\n");
            sb.Append("  IncludeDisabled: ").Append(IncludeDisabled).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
