/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// CreateChannelRequest
    /// </summary>
    [DataContract(Name = "CreateChannel_request")]
    public partial class CreateChannelRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateChannelRequest" /> class.
        /// </summary>
        /// <param name="hexColour">Hex colour for the channel mapping, for instance #FF0000 is red.</param>
        /// <param name="name">Name of the channel.</param>
        public CreateChannelRequest(string hexColour = default(string), string name = default(string))
        {
            this.HexColour = hexColour;
            this.Name = name;
        }

        /// <summary>
        /// Hex colour for the channel mapping, for instance #FF0000 is red
        /// </summary>
        /// <value>Hex colour for the channel mapping, for instance #FF0000 is red</value>
        [DataMember(Name = "HexColour", EmitDefaultValue = false)]
        public string HexColour { get; set; }

        /// <summary>
        /// Name of the channel
        /// </summary>
        /// <value>Name of the channel</value>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateChannelRequest {\n");
            sb.Append("  HexColour: ").Append(HexColour).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
