/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// DeleteUserReassignAssetsRequest
    /// </summary>
    [DataContract(Name = "DeleteUserReassignAssets_request")]
    public partial class DeleteUserReassignAssetsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteUserReassignAssetsRequest" /> class.
        /// </summary>
        /// <param name="deletedUserName">Name of the user to delete.</param>
        /// <param name="deleteLogin">flag to indicate whether associated login should be deleted.</param>
        /// <param name="reassignedUserName">Name of the user to reassign assets to.</param>
        public DeleteUserReassignAssetsRequest(string deletedUserName = default(string), bool deleteLogin = default(bool), string reassignedUserName = default(string))
        {
            this.DeletedUserName = deletedUserName;
            this.DeleteLogin = deleteLogin;
            this.ReassignedUserName = reassignedUserName;
        }

        /// <summary>
        /// Name of the user to delete
        /// </summary>
        /// <value>Name of the user to delete</value>
        [DataMember(Name = "DeletedUserName", EmitDefaultValue = false)]
        public string DeletedUserName { get; set; }

        /// <summary>
        /// flag to indicate whether associated login should be deleted
        /// </summary>
        /// <value>flag to indicate whether associated login should be deleted</value>
        [DataMember(Name = "DeleteLogin", EmitDefaultValue = true)]
        public bool DeleteLogin { get; set; }

        /// <summary>
        /// Name of the user to reassign assets to
        /// </summary>
        /// <value>Name of the user to reassign assets to</value>
        [DataMember(Name = "ReassignedUserName", EmitDefaultValue = false)]
        public string ReassignedUserName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteUserReassignAssetsRequest {\n");
            sb.Append("  DeletedUserName: ").Append(DeletedUserName).Append("\n");
            sb.Append("  DeleteLogin: ").Append(DeleteLogin).Append("\n");
            sb.Append("  ReassignedUserName: ").Append(ReassignedUserName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
