/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// DMClientSet
    /// </summary>
    [DataContract(Name = "DMClientSet")]
    public partial class DMClientSet : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DMClientSet" /> class.
        /// </summary>
        /// <param name="iD">iD.</param>
        /// <param name="name">name.</param>
        /// <param name="sASeats">sASeats.</param>
        /// <param name="defaultSettings">defaultSettings.</param>
        /// <param name="clients">clients.</param>
        /// <param name="vMTAs">vMTAs.</param>
        /// <param name="deliveryContexts">deliveryContexts.</param>
        public DMClientSet(int iD = default(int), string name = default(string), int sASeats = default(int), DMClientSettings defaultSettings = default(DMClientSettings), List<DMClient> clients = default(List<DMClient>), List<DMVMTA> vMTAs = default(List<DMVMTA>), List<DMDeliveryContext> deliveryContexts = default(List<DMDeliveryContext>))
        {
            this.ID = iD;
            this.Name = name;
            this.SASeats = sASeats;
            this.DefaultSettings = defaultSettings;
            this.Clients = clients;
            this.VMTAs = vMTAs;
            this.DeliveryContexts = deliveryContexts;
        }

        /// <summary>
        /// Gets or Sets ID
        /// </summary>
        [DataMember(Name = "ID", EmitDefaultValue = false)]
        public int ID { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets SASeats
        /// </summary>
        [DataMember(Name = "SASeats", EmitDefaultValue = false)]
        public int SASeats { get; set; }

        /// <summary>
        /// Gets or Sets DefaultSettings
        /// </summary>
        [DataMember(Name = "DefaultSettings", EmitDefaultValue = false)]
        public DMClientSettings DefaultSettings { get; set; }

        /// <summary>
        /// Gets or Sets Clients
        /// </summary>
        [DataMember(Name = "Clients", EmitDefaultValue = false)]
        public List<DMClient> Clients { get; set; }

        /// <summary>
        /// Gets or Sets VMTAs
        /// </summary>
        [DataMember(Name = "VMTAs", EmitDefaultValue = false)]
        public List<DMVMTA> VMTAs { get; set; }

        /// <summary>
        /// Gets or Sets DeliveryContexts
        /// </summary>
        [DataMember(Name = "DeliveryContexts", EmitDefaultValue = false)]
        public List<DMDeliveryContext> DeliveryContexts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DMClientSet {\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SASeats: ").Append(SASeats).Append("\n");
            sb.Append("  DefaultSettings: ").Append(DefaultSettings).Append("\n");
            sb.Append("  Clients: ").Append(Clients).Append("\n");
            sb.Append("  VMTAs: ").Append(VMTAs).Append("\n");
            sb.Append("  DeliveryContexts: ").Append(DeliveryContexts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
