/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// Provides details of an EM Client
    /// </summary>
    [DataContract(Name = "EMClient")]
    public partial class EMClient : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EMClient" /> class.
        /// </summary>
        /// <param name="id">Unique ID of this client.</param>
        /// <param name="siteId">Site ID.</param>
        /// <param name="eMClientId">Id of this client.</param>
        /// <param name="name">Name of this client.</param>
        /// <param name="canEdit">Does the client have edit permissions for this user - cannot set this value using this property.</param>
        public EMClient(int id = default(int), int siteId = default(int), int eMClientId = default(int), string name = default(string), int canEdit = default(int))
        {
            this.Id = id;
            this.SiteId = siteId;
            this.EMClientId = eMClientId;
            this.Name = name;
            this.CanEdit = canEdit;
        }

        /// <summary>
        /// Unique ID of this client
        /// </summary>
        /// <value>Unique ID of this client</value>
        [DataMember(Name = "Id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Site ID
        /// </summary>
        /// <value>Site ID</value>
        [DataMember(Name = "SiteId", EmitDefaultValue = false)]
        public int SiteId { get; set; }

        /// <summary>
        /// Id of this client
        /// </summary>
        /// <value>Id of this client</value>
        [DataMember(Name = "EMClientId", EmitDefaultValue = false)]
        public int EMClientId { get; set; }

        /// <summary>
        /// Name of this client
        /// </summary>
        /// <value>Name of this client</value>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Does the client have edit permissions for this user - cannot set this value using this property
        /// </summary>
        /// <value>Does the client have edit permissions for this user - cannot set this value using this property</value>
        [DataMember(Name = "CanEdit", EmitDefaultValue = false)]
        public int CanEdit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EMClient {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("  EMClientId: ").Append(EMClientId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CanEdit: ").Append(CanEdit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
