/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// GetEMMappingsRequest
    /// </summary>
    [DataContract(Name = "GetEMMappings_request")]
    public partial class GetEMMappingsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEMMappingsRequest" /> class.
        /// </summary>
        /// <param name="cursor">cursor.</param>
        /// <param name="folderID">@see(Folder) from which to return the list of @see(EMMapping)s.  Pass NULL for the root [not contained within a folder].</param>
        /// <param name="includeChildren">pass TRUE to find any @see(EMUploadMapping)s which are contained within child folders of the FolderID parameter.</param>
        public GetEMMappingsRequest(APICursor cursor = default(APICursor), int? folderID = default(int?), bool includeChildren = default(bool))
        {
            this.Cursor = cursor;
            this.FolderID = folderID;
            this.IncludeChildren = includeChildren;
        }

        /// <summary>
        /// Gets or Sets Cursor
        /// </summary>
        [DataMember(Name = "Cursor", EmitDefaultValue = false)]
        public APICursor Cursor { get; set; }

        /// <summary>
        /// @see(Folder) from which to return the list of @see(EMMapping)s.  Pass NULL for the root [not contained within a folder]
        /// </summary>
        /// <value>@see(Folder) from which to return the list of @see(EMMapping)s.  Pass NULL for the root [not contained within a folder]</value>
        [DataMember(Name = "FolderID", EmitDefaultValue = true)]
        public int? FolderID { get; set; }

        /// <summary>
        /// pass TRUE to find any @see(EMUploadMapping)s which are contained within child folders of the FolderID parameter
        /// </summary>
        /// <value>pass TRUE to find any @see(EMUploadMapping)s which are contained within child folders of the FolderID parameter</value>
        [DataMember(Name = "IncludeChildren", EmitDefaultValue = true)]
        public bool IncludeChildren { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEMMappingsRequest {\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("  FolderID: ").Append(FolderID).Append("\n");
            sb.Append("  IncludeChildren: ").Append(IncludeChildren).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
