/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.JA.Client.OpenAPIDateConverter;

namespace Alterian.JA.Model
{
    /// <summary>
    /// UpdateClientSettingsRequest
    /// </summary>
    [DataContract(Name = "UpdateClientSettings_request")]
    public partial class UpdateClientSettingsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateClientSettingsRequest" /> class.
        /// </summary>
        /// <param name="clientId">Id of client to return.</param>
        /// <param name="settings">Updated client settings e.g.[ { \&quot;Key\&quot;: \&quot;activitylogbatchsize\&quot;, \&quot;Value\&quot;: \&quot;500\&quot; } ].</param>
        public UpdateClientSettingsRequest(int clientId = default(int), Dictionary<string, string> settings = default(Dictionary<string, string>))
        {
            this.ClientId = clientId;
            this.Settings = settings;
        }

        /// <summary>
        /// Id of client to return
        /// </summary>
        /// <value>Id of client to return</value>
        [DataMember(Name = "ClientId", EmitDefaultValue = false)]
        public int ClientId { get; set; }

        /// <summary>
        /// Updated client settings e.g.[ { \&quot;Key\&quot;: \&quot;activitylogbatchsize\&quot;, \&quot;Value\&quot;: \&quot;500\&quot; } ]
        /// </summary>
        /// <value>Updated client settings e.g.[ { \&quot;Key\&quot;: \&quot;activitylogbatchsize\&quot;, \&quot;Value\&quot;: \&quot;500\&quot; } ]</value>
        [DataMember(Name = "Settings", EmitDefaultValue = false)]
        public Dictionary<string, string> Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateClientSettingsRequest {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
