/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing APIFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class APIFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for APIFilter
        //private APIFilter instance;

        public APIFilterTests()
        {
            // TODO uncomment below to create an instance of APIFilter
            //instance = new APIFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of APIFilter
        /// </summary>
        [Fact]
        public void APIFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" APIFilter
            //Assert.IsType<APIFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Predicate'
        /// </summary>
        [Fact]
        public void PredicateTest()
        {
            // TODO unit test for the property 'Predicate'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'DataSourceID'
        /// </summary>
        [Fact]
        public void DataSourceIDTest()
        {
            // TODO unit test for the property 'DataSourceID'
        }

        /// <summary>
        /// Test the property 'DatabaseID'
        /// </summary>
        [Fact]
        public void DatabaseIDTest()
        {
            // TODO unit test for the property 'DatabaseID'
        }

        /// <summary>
        /// Test the property 'TableID'
        /// </summary>
        [Fact]
        public void TableIDTest()
        {
            // TODO unit test for the property 'TableID'
        }
    }
}
