/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing BusinessGoalKPI
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BusinessGoalKPITests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BusinessGoalKPI
        //private BusinessGoalKPI instance;

        public BusinessGoalKPITests()
        {
            // TODO uncomment below to create an instance of BusinessGoalKPI
            //instance = new BusinessGoalKPI();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BusinessGoalKPI
        /// </summary>
        [Fact]
        public void BusinessGoalKPIInstanceTest()
        {
            // TODO uncomment below to test "IsType" BusinessGoalKPI
            //Assert.IsType<BusinessGoalKPI>(instance);
        }

        /// <summary>
        /// Test the property 'MetricID'
        /// </summary>
        [Fact]
        public void MetricIDTest()
        {
            // TODO unit test for the property 'MetricID'
        }

        /// <summary>
        /// Test the property 'Polarity'
        /// </summary>
        [Fact]
        public void PolarityTest()
        {
            // TODO unit test for the property 'Polarity'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
    }
}
