/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing CMTokenInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CMTokenInformationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CMTokenInformation
        //private CMTokenInformation instance;

        public CMTokenInformationTests()
        {
            // TODO uncomment below to create an instance of CMTokenInformation
            //instance = new CMTokenInformation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CMTokenInformation
        /// </summary>
        [Fact]
        public void CMTokenInformationInstanceTest()
        {
            // TODO uncomment below to test "IsType" CMTokenInformation
            //Assert.IsType<CMTokenInformation>(instance);
        }

        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

        /// <summary>
        /// Test the property 'LoginID'
        /// </summary>
        [Fact]
        public void LoginIDTest()
        {
            // TODO unit test for the property 'LoginID'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'TimezoneID'
        /// </summary>
        [Fact]
        public void TimezoneIDTest()
        {
            // TODO unit test for the property 'TimezoneID'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'ClientID'
        /// </summary>
        [Fact]
        public void ClientIDTest()
        {
            // TODO unit test for the property 'ClientID'
        }

        /// <summary>
        /// Test the property 'LastActivity'
        /// </summary>
        [Fact]
        public void LastActivityTest()
        {
            // TODO unit test for the property 'LastActivity'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Culture'
        /// </summary>
        [Fact]
        public void CultureTest()
        {
            // TODO unit test for the property 'Culture'
        }

        /// <summary>
        /// Test the property 'IsStatic'
        /// </summary>
        [Fact]
        public void IsStaticTest()
        {
            // TODO unit test for the property 'IsStatic'
        }

        /// <summary>
        /// Test the property 'IsSAtoken'
        /// </summary>
        [Fact]
        public void IsSAtokenTest()
        {
            // TODO unit test for the property 'IsSAtoken'
        }
    }
}
