/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEventStreamRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEventStreamRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEventStreamRequest
        //private CreateEventStreamRequest instance;

        public CreateEventStreamRequestTests()
        {
            // TODO uncomment below to create an instance of CreateEventStreamRequest
            //instance = new CreateEventStreamRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEventStreamRequest
        /// </summary>
        [Fact]
        public void CreateEventStreamRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEventStreamRequest
            //Assert.IsType<CreateEventStreamRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DDEClient'
        /// </summary>
        [Fact]
        public void DDEClientTest()
        {
            // TODO unit test for the property 'DDEClient'
        }

        /// <summary>
        /// Test the property 'DDESiteId'
        /// </summary>
        [Fact]
        public void DDESiteIdTest()
        {
            // TODO unit test for the property 'DDESiteId'
        }

        /// <summary>
        /// Test the property 'DDETarget'
        /// </summary>
        [Fact]
        public void DDETargetTest()
        {
            // TODO unit test for the property 'DDETarget'
        }

        /// <summary>
        /// Test the property 'EventStreamDatabase'
        /// </summary>
        [Fact]
        public void EventStreamDatabaseTest()
        {
            // TODO unit test for the property 'EventStreamDatabase'
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'IsFifoQueueRequired'
        /// </summary>
        [Fact]
        public void IsFifoQueueRequiredTest()
        {
            // TODO unit test for the property 'IsFifoQueueRequired'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Fact]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }

        /// <summary>
        /// Test the property 'QueueLockId'
        /// </summary>
        [Fact]
        public void QueueLockIdTest()
        {
            // TODO unit test for the property 'QueueLockId'
        }

        /// <summary>
        /// Test the property 'Server'
        /// </summary>
        [Fact]
        public void ServerTest()
        {
            // TODO unit test for the property 'Server'
        }

        /// <summary>
        /// Test the property 'SkipDefaultQueueSetup'
        /// </summary>
        [Fact]
        public void SkipDefaultQueueSetupTest()
        {
            // TODO unit test for the property 'SkipDefaultQueueSetup'
        }
    }
}
