/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEMMappingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEMMappingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEMMappingRequest
        //private CreateEMMappingRequest instance;

        public CreateEMMappingRequestTests()
        {
            // TODO uncomment below to create an instance of CreateEMMappingRequest
            //instance = new CreateEMMappingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEMMappingRequest
        /// </summary>
        [Fact]
        public void CreateEMMappingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEMMappingRequest
            //Assert.IsType<CreateEMMappingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Mapping'
        /// </summary>
        [Fact]
        public void MappingTest()
        {
            // TODO unit test for the property 'Mapping'
        }
    }
}
