/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteInitiativeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteInitiativeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteInitiativeRequest
        //private DeleteInitiativeRequest instance;

        public DeleteInitiativeRequestTests()
        {
            // TODO uncomment below to create an instance of DeleteInitiativeRequest
            //instance = new DeleteInitiativeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteInitiativeRequest
        /// </summary>
        [Fact]
        public void DeleteInitiativeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteInitiativeRequest
            //Assert.IsType<DeleteInitiativeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
