/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing DMOmnitureSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DMOmnitureSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DMOmnitureSettings
        //private DMOmnitureSettings instance;

        public DMOmnitureSettingsTests()
        {
            // TODO uncomment below to create an instance of DMOmnitureSettings
            //instance = new DMOmnitureSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DMOmnitureSettings
        /// </summary>
        [Fact]
        public void DMOmnitureSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DMOmnitureSettings
            //Assert.IsType<DMOmnitureSettings>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'IntegrationNum'
        /// </summary>
        [Fact]
        public void IntegrationNumTest()
        {
            // TODO unit test for the property 'IntegrationNum'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'ReportSuite'
        /// </summary>
        [Fact]
        public void ReportSuiteTest()
        {
            // TODO unit test for the property 'ReportSuite'
        }

        /// <summary>
        /// Test the property 'RemarketingSegPath'
        /// </summary>
        [Fact]
        public void RemarketingSegPathTest()
        {
            // TODO unit test for the property 'RemarketingSegPath'
        }

        /// <summary>
        /// Test the property 'RemarketingSeg'
        /// </summary>
        [Fact]
        public void RemarketingSegTest()
        {
            // TODO unit test for the property 'RemarketingSeg'
        }

        /// <summary>
        /// Test the property 'EmailAddr'
        /// </summary>
        [Fact]
        public void EmailAddrTest()
        {
            // TODO unit test for the property 'EmailAddr'
        }
    }
}
