/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing DMVMTA
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DMVMTATests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DMVMTA
        //private DMVMTA instance;

        public DMVMTATests()
        {
            // TODO uncomment below to create an instance of DMVMTA
            //instance = new DMVMTA();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DMVMTA
        /// </summary>
        [Fact]
        public void DMVMTAInstanceTest()
        {
            // TODO uncomment below to test "IsType" DMVMTA
            //Assert.IsType<DMVMTA>(instance);
        }

        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'IP'
        /// </summary>
        [Fact]
        public void IPTest()
        {
            // TODO unit test for the property 'IP'
        }

        /// <summary>
        /// Test the property 'MTAServerID'
        /// </summary>
        [Fact]
        public void MTAServerIDTest()
        {
            // TODO unit test for the property 'MTAServerID'
        }
    }
}
