/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing EMDeleteListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EMDeleteListRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EMDeleteListRequest
        //private EMDeleteListRequest instance;

        public EMDeleteListRequestTests()
        {
            // TODO uncomment below to create an instance of EMDeleteListRequest
            //instance = new EMDeleteListRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EMDeleteListRequest
        /// </summary>
        [Fact]
        public void EMDeleteListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EMDeleteListRequest
            //Assert.IsType<EMDeleteListRequest>(instance);
        }

        /// <summary>
        /// Test the property 'EMMappingId'
        /// </summary>
        [Fact]
        public void EMMappingIdTest()
        {
            // TODO unit test for the property 'EMMappingId'
        }

        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Fact]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }
    }
}
