/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing EMDocumentActivityType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EMDocumentActivityTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EMDocumentActivityType
        //private EMDocumentActivityType instance;

        public EMDocumentActivityTypeTests()
        {
            // TODO uncomment below to create an instance of EMDocumentActivityType
            //instance = new EMDocumentActivityType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EMDocumentActivityType
        /// </summary>
        [Fact]
        public void EMDocumentActivityTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EMDocumentActivityType
            //Assert.IsType<EMDocumentActivityType>(instance);
        }
    }
}
