/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing EMGetTemplateContentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EMGetTemplateContentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EMGetTemplateContentRequest
        //private EMGetTemplateContentRequest instance;

        public EMGetTemplateContentRequestTests()
        {
            // TODO uncomment below to create an instance of EMGetTemplateContentRequest
            //instance = new EMGetTemplateContentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EMGetTemplateContentRequest
        /// </summary>
        [Fact]
        public void EMGetTemplateContentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EMGetTemplateContentRequest
            //Assert.IsType<EMGetTemplateContentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'CreativeId'
        /// </summary>
        [Fact]
        public void CreativeIdTest()
        {
            // TODO unit test for the property 'CreativeId'
        }

        /// <summary>
        /// Test the property 'EMMappingId'
        /// </summary>
        [Fact]
        public void EMMappingIdTest()
        {
            // TODO unit test for the property 'EMMappingId'
        }

        /// <summary>
        /// Test the property 'IsForPreviewOrDesignView'
        /// </summary>
        [Fact]
        public void IsForPreviewOrDesignViewTest()
        {
            // TODO unit test for the property 'IsForPreviewOrDesignView'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
    }
}
