/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing EMGetUsersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EMGetUsersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EMGetUsersRequest
        //private EMGetUsersRequest instance;

        public EMGetUsersRequestTests()
        {
            // TODO uncomment below to create an instance of EMGetUsersRequest
            //instance = new EMGetUsersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EMGetUsersRequest
        /// </summary>
        [Fact]
        public void EMGetUsersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EMGetUsersRequest
            //Assert.IsType<EMGetUsersRequest>(instance);
        }

        /// <summary>
        /// Test the property 'EMMappingId'
        /// </summary>
        [Fact]
        public void EMMappingIdTest()
        {
            // TODO unit test for the property 'EMMappingId'
        }

        /// <summary>
        /// Test the property 'EMSiteId'
        /// </summary>
        [Fact]
        public void EMSiteIdTest()
        {
            // TODO unit test for the property 'EMSiteId'
        }

        /// <summary>
        /// Test the property 'EMToken'
        /// </summary>
        [Fact]
        public void EMTokenTest()
        {
            // TODO unit test for the property 'EMToken'
        }
    }
}
