/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing EventStreamField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventStreamFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventStreamField
        //private EventStreamField instance;

        public EventStreamFieldTests()
        {
            // TODO uncomment below to create an instance of EventStreamField
            //instance = new EventStreamField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventStreamField
        /// </summary>
        [Fact]
        public void EventStreamFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventStreamField
            //Assert.IsType<EventStreamField>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'IndexLevel'
        /// </summary>
        [Fact]
        public void IndexLevelTest()
        {
            // TODO unit test for the property 'IndexLevel'
        }

        /// <summary>
        /// Test the property 'StorageHint'
        /// </summary>
        [Fact]
        public void StorageHintTest()
        {
            // TODO unit test for the property 'StorageHint'
        }

        /// <summary>
        /// Test the property 'IsKey'
        /// </summary>
        [Fact]
        public void IsKeyTest()
        {
            // TODO unit test for the property 'IsKey'
        }

        /// <summary>
        /// Test the property 'KeyName'
        /// </summary>
        [Fact]
        public void KeyNameTest()
        {
            // TODO unit test for the property 'KeyName'
        }

        /// <summary>
        /// Test the property 'IsSystem'
        /// </summary>
        [Fact]
        public void IsSystemTest()
        {
            // TODO unit test for the property 'IsSystem'
        }

        /// <summary>
        /// Test the property 'Precision'
        /// </summary>
        [Fact]
        public void PrecisionTest()
        {
            // TODO unit test for the property 'Precision'
        }

        /// <summary>
        /// Test the property 'IsSankey'
        /// </summary>
        [Fact]
        public void IsSankeyTest()
        {
            // TODO unit test for the property 'IsSankey'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

        /// <summary>
        /// Test the property 'NumDiscretes'
        /// </summary>
        [Fact]
        public void NumDiscretesTest()
        {
            // TODO unit test for the property 'NumDiscretes'
        }

        /// <summary>
        /// Test the property 'FieldTransformLists'
        /// </summary>
        [Fact]
        public void FieldTransformListsTest()
        {
            // TODO unit test for the property 'FieldTransformLists'
        }

        /// <summary>
        /// Test the property 'ColumnName'
        /// </summary>
        [Fact]
        public void ColumnNameTest()
        {
            // TODO unit test for the property 'ColumnName'
        }
    }
}
