/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing EventStreamAlignmentType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventStreamAlignmentTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventStreamAlignmentType
        //private EventStreamAlignmentType instance;

        public EventStreamAlignmentTypeTests()
        {
            // TODO uncomment below to create an instance of EventStreamAlignmentType
            //instance = new EventStreamAlignmentType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventStreamAlignmentType
        /// </summary>
        [Fact]
        public void EventStreamAlignmentTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventStreamAlignmentType
            //Assert.IsType<EventStreamAlignmentType>(instance);
        }
    }
}
