/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing GetEventStreamInitiativesDefaultResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEventStreamInitiativesDefaultResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEventStreamInitiativesDefaultResponse
        //private GetEventStreamInitiativesDefaultResponse instance;

        public GetEventStreamInitiativesDefaultResponseTests()
        {
            // TODO uncomment below to create an instance of GetEventStreamInitiativesDefaultResponse
            //instance = new GetEventStreamInitiativesDefaultResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEventStreamInitiativesDefaultResponse
        /// </summary>
        [Fact]
        public void GetEventStreamInitiativesDefaultResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEventStreamInitiativesDefaultResponse
            //Assert.IsType<GetEventStreamInitiativesDefaultResponse>(instance);
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

        /// <summary>
        /// Test the property 'DebugMessage'
        /// </summary>
        [Fact]
        public void DebugMessageTest()
        {
            // TODO unit test for the property 'DebugMessage'
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
