/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing GetEventStreamModelsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEventStreamModelsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEventStreamModelsRequest
        //private GetEventStreamModelsRequest instance;

        public GetEventStreamModelsRequestTests()
        {
            // TODO uncomment below to create an instance of GetEventStreamModelsRequest
            //instance = new GetEventStreamModelsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEventStreamModelsRequest
        /// </summary>
        [Fact]
        public void GetEventStreamModelsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEventStreamModelsRequest
            //Assert.IsType<GetEventStreamModelsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'EventStreamId'
        /// </summary>
        [Fact]
        public void EventStreamIdTest()
        {
            // TODO unit test for the property 'EventStreamId'
        }

        /// <summary>
        /// Test the property 'IncludePublic'
        /// </summary>
        [Fact]
        public void IncludePublicTest()
        {
            // TODO unit test for the property 'IncludePublic'
        }

        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Fact]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
