/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing GetEventRecordsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEventRecordsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEventRecordsRequest
        //private GetEventRecordsRequest instance;

        public GetEventRecordsRequestTests()
        {
            // TODO uncomment below to create an instance of GetEventRecordsRequest
            //instance = new GetEventRecordsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEventRecordsRequest
        /// </summary>
        [Fact]
        public void GetEventRecordsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEventRecordsRequest
            //Assert.IsType<GetEventRecordsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ColumnTransforms'
        /// </summary>
        [Fact]
        public void ColumnTransformsTest()
        {
            // TODO unit test for the property 'ColumnTransforms'
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'DataSourceId'
        /// </summary>
        [Fact]
        public void DataSourceIdTest()
        {
            // TODO unit test for the property 'DataSourceId'
        }

        /// <summary>
        /// Test the property 'EventDateTimeLower'
        /// </summary>
        [Fact]
        public void EventDateTimeLowerTest()
        {
            // TODO unit test for the property 'EventDateTimeLower'
        }

        /// <summary>
        /// Test the property 'EventDateTimeUpper'
        /// </summary>
        [Fact]
        public void EventDateTimeUpperTest()
        {
            // TODO unit test for the property 'EventDateTimeUpper'
        }

        /// <summary>
        /// Test the property 'EventTypes'
        /// </summary>
        [Fact]
        public void EventTypesTest()
        {
            // TODO unit test for the property 'EventTypes'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'Initiatives'
        /// </summary>
        [Fact]
        public void InitiativesTest()
        {
            // TODO unit test for the property 'Initiatives'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'TableNameEx'
        /// </summary>
        [Fact]
        public void TableNameExTest()
        {
            // TODO unit test for the property 'TableNameEx'
        }
    }
}
