/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing GetFoldersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetFoldersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetFoldersRequest
        //private GetFoldersRequest instance;

        public GetFoldersRequestTests()
        {
            // TODO uncomment below to create an instance of GetFoldersRequest
            //instance = new GetFoldersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetFoldersRequest
        /// </summary>
        [Fact]
        public void GetFoldersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetFoldersRequest
            //Assert.IsType<GetFoldersRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'FolderType'
        /// </summary>
        [Fact]
        public void FolderTypeTest()
        {
            // TODO unit test for the property 'FolderType'
        }

        /// <summary>
        /// Test the property 'GetChildFolders'
        /// </summary>
        [Fact]
        public void GetChildFoldersTest()
        {
            // TODO unit test for the property 'GetChildFolders'
        }

        /// <summary>
        /// Test the property 'IncludeChildCount'
        /// </summary>
        [Fact]
        public void IncludeChildCountTest()
        {
            // TODO unit test for the property 'IncludeChildCount'
        }

        /// <summary>
        /// Test the property 'IncludeHidden'
        /// </summary>
        [Fact]
        public void IncludeHiddenTest()
        {
            // TODO unit test for the property 'IncludeHidden'
        }

        /// <summary>
        /// Test the property 'ParentFolder'
        /// </summary>
        [Fact]
        public void ParentFolderTest()
        {
            // TODO unit test for the property 'ParentFolder'
        }
    }
}
