/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing GetPatternRecordsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPatternRecordsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPatternRecordsRequest
        //private GetPatternRecordsRequest instance;

        public GetPatternRecordsRequestTests()
        {
            // TODO uncomment below to create an instance of GetPatternRecordsRequest
            //instance = new GetPatternRecordsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPatternRecordsRequest
        /// </summary>
        [Fact]
        public void GetPatternRecordsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPatternRecordsRequest
            //Assert.IsType<GetPatternRecordsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'PatternId'
        /// </summary>
        [Fact]
        public void PatternIdTest()
        {
            // TODO unit test for the property 'PatternId'
        }
    }
}
