/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing GetTokensRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTokensRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTokensRequest
        //private GetTokensRequest instance;

        public GetTokensRequestTests()
        {
            // TODO uncomment below to create an instance of GetTokensRequest
            //instance = new GetTokensRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTokensRequest
        /// </summary>
        [Fact]
        public void GetTokensRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTokensRequest
            //Assert.IsType<GetTokensRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientID'
        /// </summary>
        [Fact]
        public void ClientIDTest()
        {
            // TODO unit test for the property 'ClientID'
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'IncludeNonUser'
        /// </summary>
        [Fact]
        public void IncludeNonUserTest()
        {
            // TODO unit test for the property 'IncludeNonUser'
        }

        /// <summary>
        /// Test the property 'IncludeSA'
        /// </summary>
        [Fact]
        public void IncludeSATest()
        {
            // TODO unit test for the property 'IncludeSA'
        }

        /// <summary>
        /// Test the property 'IncludeStandard'
        /// </summary>
        [Fact]
        public void IncludeStandardTest()
        {
            // TODO unit test for the property 'IncludeStandard'
        }

        /// <summary>
        /// Test the property 'IncludeStatic'
        /// </summary>
        [Fact]
        public void IncludeStaticTest()
        {
            // TODO unit test for the property 'IncludeStatic'
        }
    }
}
