/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing OpportunityItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpportunityItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpportunityItem
        //private OpportunityItem instance;

        public OpportunityItemTests()
        {
            // TODO uncomment below to create an instance of OpportunityItem
            //instance = new OpportunityItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpportunityItem
        /// </summary>
        [Fact]
        public void OpportunityItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" OpportunityItem
            //Assert.IsType<OpportunityItem>(instance);
        }

        /// <summary>
        /// Test the property 'OpportunityId'
        /// </summary>
        [Fact]
        public void OpportunityIdTest()
        {
            // TODO unit test for the property 'OpportunityId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
