/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing SequencePredictorPredictionOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SequencePredictorPredictionOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SequencePredictorPredictionOptions
        //private SequencePredictorPredictionOptions instance;

        public SequencePredictorPredictionOptionsTests()
        {
            // TODO uncomment below to create an instance of SequencePredictorPredictionOptions
            //instance = new SequencePredictorPredictionOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SequencePredictorPredictionOptions
        /// </summary>
        [Fact]
        public void SequencePredictorPredictionOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SequencePredictorPredictionOptions
            //Assert.IsType<SequencePredictorPredictionOptions>(instance);
        }

        /// <summary>
        /// Test the property 'PredictionName'
        /// </summary>
        [Fact]
        public void PredictionNameTest()
        {
            // TODO unit test for the property 'PredictionName'
        }

        /// <summary>
        /// Test the property 'PredictionSeedOutputOption'
        /// </summary>
        [Fact]
        public void PredictionSeedOutputOptionTest()
        {
            // TODO unit test for the property 'PredictionSeedOutputOption'
        }

        /// <summary>
        /// Test the property 'PredictionSelectionMode'
        /// </summary>
        [Fact]
        public void PredictionSelectionModeTest()
        {
            // TODO unit test for the property 'PredictionSelectionMode'
        }

        /// <summary>
        /// Test the property 'NumberOfPredictions'
        /// </summary>
        [Fact]
        public void NumberOfPredictionsTest()
        {
            // TODO unit test for the property 'NumberOfPredictions'
        }

        /// <summary>
        /// Test the property 'IsDataDebugRequired'
        /// </summary>
        [Fact]
        public void IsDataDebugRequiredTest()
        {
            // TODO unit test for the property 'IsDataDebugRequired'
        }
    }
}
