/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing SetLoginUserMappingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetLoginUserMappingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetLoginUserMappingRequest
        //private SetLoginUserMappingRequest instance;

        public SetLoginUserMappingRequestTests()
        {
            // TODO uncomment below to create an instance of SetLoginUserMappingRequest
            //instance = new SetLoginUserMappingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetLoginUserMappingRequest
        /// </summary>
        [Fact]
        public void SetLoginUserMappingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetLoginUserMappingRequest
            //Assert.IsType<SetLoginUserMappingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
