/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing SetPermissionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetPermissionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetPermissionsRequest
        //private SetPermissionsRequest instance;

        public SetPermissionsRequestTests()
        {
            // TODO uncomment below to create an instance of SetPermissionsRequest
            //instance = new SetPermissionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetPermissionsRequest
        /// </summary>
        [Fact]
        public void SetPermissionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetPermissionsRequest
            //Assert.IsType<SetPermissionsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'IsGroup'
        /// </summary>
        [Fact]
        public void IsGroupTest()
        {
            // TODO unit test for the property 'IsGroup'
        }

        /// <summary>
        /// Test the property 'ItemID'
        /// </summary>
        [Fact]
        public void ItemIDTest()
        {
            // TODO unit test for the property 'ItemID'
        }

        /// <summary>
        /// Test the property 'ItemType'
        /// </summary>
        [Fact]
        public void ItemTypeTest()
        {
            // TODO unit test for the property 'ItemType'
        }

        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

        /// <summary>
        /// Test the property 'SecurityID'
        /// </summary>
        [Fact]
        public void SecurityIDTest()
        {
            // TODO unit test for the property 'SecurityID'
        }
    }
}
