/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing TakeOwnershipPermissionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TakeOwnershipPermissionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TakeOwnershipPermissionRequest
        //private TakeOwnershipPermissionRequest instance;

        public TakeOwnershipPermissionRequestTests()
        {
            // TODO uncomment below to create an instance of TakeOwnershipPermissionRequest
            //instance = new TakeOwnershipPermissionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TakeOwnershipPermissionRequest
        /// </summary>
        [Fact]
        public void TakeOwnershipPermissionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TakeOwnershipPermissionRequest
            //Assert.IsType<TakeOwnershipPermissionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ItemID'
        /// </summary>
        [Fact]
        public void ItemIDTest()
        {
            // TODO unit test for the property 'ItemID'
        }

        /// <summary>
        /// Test the property 'ItemType'
        /// </summary>
        [Fact]
        public void ItemTypeTest()
        {
            // TODO unit test for the property 'ItemType'
        }

        /// <summary>
        /// Test the property 'NewOwnerID'
        /// </summary>
        [Fact]
        public void NewOwnerIDTest()
        {
            // TODO unit test for the property 'NewOwnerID'
        }
    }
}
