/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateSystemSettingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSystemSettingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateSystemSettingRequest
        //private UpdateSystemSettingRequest instance;

        public UpdateSystemSettingRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateSystemSettingRequest
            //instance = new UpdateSystemSettingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateSystemSettingRequest
        /// </summary>
        [Fact]
        public void UpdateSystemSettingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateSystemSettingRequest
            //Assert.IsType<UpdateSystemSettingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
