/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.JA.Model;
using Alterian.JA.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.JA.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateClientSettingsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateClientSettingsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateClientSettingsRequest
        //private UpdateClientSettingsRequest instance;

        public UpdateClientSettingsRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateClientSettingsRequest
            //instance = new UpdateClientSettingsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateClientSettingsRequest
        /// </summary>
        [Fact]
        public void UpdateClientSettingsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateClientSettingsRequest
            //Assert.IsType<UpdateClientSettingsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
    }
}
