/*
 * Journey Analytics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Alterian.JA.Client;
using Alterian.JA.Api;
// uncomment below to import models
//using Alterian.JA.Model;

namespace Alterian.JA.Test.Api
{
    /// <summary>
    ///  Class for testing EmailManagerMappingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailManagerMappingApiTests : IDisposable
    {
        private EmailManagerMappingApi instance;

        public EmailManagerMappingApiTests()
        {
            instance = new EmailManagerMappingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailManagerMappingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailManagerMappingApi
            //Assert.IsType<EmailManagerMappingApi>(instance);
        }

        /// <summary>
        /// Test CreateEMMapping
        /// </summary>
        [Fact]
        public void CreateEMMappingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEMMappingRequest createEMMappingRequest = null;
            //var response = instance.CreateEMMapping(createEMMappingRequest);
            //Assert.IsType<CreateClientDefaultResponse>(response);
        }

        /// <summary>
        /// Test CreateEMSession
        /// </summary>
        [Fact]
        public void CreateEMSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEMSessionRequest createEMSessionRequest = null;
            //var response = instance.CreateEMSession(createEMSessionRequest);
            //Assert.IsType<CreateEMSessionDefaultResponse>(response);
        }

        /// <summary>
        /// Test DeleteEMMapping
        /// </summary>
        [Fact]
        public void DeleteEMMappingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeleteEMMappingRequest deleteEMMappingRequest = null;
            //var response = instance.DeleteEMMapping(deleteEMMappingRequest);
            //Assert.IsType<AUTHChangePasswordDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetEMDownloadMappings
        /// </summary>
        [Fact]
        public void GetEMDownloadMappingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetClientSetsRequest getClientSetsRequest = null;
            //var response = instance.GetEMDownloadMappings(getClientSetsRequest);
            //Assert.IsType<GetEMDownloadMappingsDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetEMMapping
        /// </summary>
        [Fact]
        public void GetEMMappingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetEMMappingRequest getEMMappingRequest = null;
            //var response = instance.GetEMMapping(getEMMappingRequest);
            //Assert.IsType<GetEMMappingDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetEMMappings
        /// </summary>
        [Fact]
        public void GetEMMappingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetEMMappingsRequest getEMMappingsRequest = null;
            //var response = instance.GetEMMappings(getEMMappingsRequest);
            //Assert.IsType<GetEMMappingsDefaultResponse>(response);
        }

        /// <summary>
        /// Test MoveEMMapping
        /// </summary>
        [Fact]
        public void MoveEMMappingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MoveEMMappingRequest moveEMMappingRequest = null;
            //var response = instance.MoveEMMapping(moveEMMappingRequest);
            //Assert.IsType<AUTHChangePasswordDefaultResponse>(response);
        }

        /// <summary>
        /// Test RenameEMMapping
        /// </summary>
        [Fact]
        public void RenameEMMappingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RenameEMMappingRequest renameEMMappingRequest = null;
            //var response = instance.RenameEMMapping(renameEMMappingRequest);
            //Assert.IsType<AUTHChangePasswordDefaultResponse>(response);
        }

        /// <summary>
        /// Test UpdateEMMapping
        /// </summary>
        [Fact]
        public void UpdateEMMappingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEMMappingRequest createEMMappingRequest = null;
            //var response = instance.UpdateEMMapping(createEMMappingRequest);
            //Assert.IsType<AUTHChangePasswordDefaultResponse>(response);
        }
    }
}
